/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVisionRouteImport } from './routes/api/vision'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiGenerateVideoRouteImport } from './routes/api/generate-video'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiEditImageRouteImport } from './routes/api/edit-image'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedVisionRouteImport } from './routes/_authenticated/vision'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScreenRouteImport } from './routes/_authenticated/screen'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated/media'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedArRouteImport } from './routes/_authenticated/ar'
import { Route as ApiTtsLovableRouteImport } from './routes/api/tts.lovable'
import { Route as ApiTtsElevenlabsRouteImport } from './routes/api/tts.elevenlabs'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisionRoute = ApiVisionRouteImport.update({
  id: '/api/vision',
  path: '/api/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateVideoRoute = ApiGenerateVideoRouteImport.update({
  id: '/api/generate-video',
  path: '/api/generate-video',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEditImageRoute = ApiEditImageRouteImport.update({
  id: '/api/edit-image',
  path: '/api/edit-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisionRoute = AuthenticatedVisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScreenRoute = AuthenticatedScreenRouteImport.update({
  id: '/screen',
  path: '/screen',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedArRoute = AuthenticatedArRouteImport.update({
  id: '/ar',
  path: '/ar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiTtsLovableRoute = ApiTtsLovableRouteImport.update({
  id: '/api/tts/lovable',
  path: '/api/tts/lovable',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsElevenlabsRoute = ApiTtsElevenlabsRouteImport.update({
  id: '/api/tts/elevenlabs',
  path: '/api/tts/elevenlabs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ar': typeof AuthenticatedArRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/library': typeof AuthenticatedLibraryRoute
  '/media': typeof AuthenticatedMediaRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/screen': typeof AuthenticatedScreenRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/vision': typeof AuthenticatedVisionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/edit-image': typeof ApiEditImageRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/stt': typeof ApiSttRoute
  '/api/vision': typeof ApiVisionRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/tts/elevenlabs': typeof ApiTtsElevenlabsRoute
  '/api/tts/lovable': typeof ApiTtsLovableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ar': typeof AuthenticatedArRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/library': typeof AuthenticatedLibraryRoute
  '/media': typeof AuthenticatedMediaRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/screen': typeof AuthenticatedScreenRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/vision': typeof AuthenticatedVisionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/edit-image': typeof ApiEditImageRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/stt': typeof ApiSttRoute
  '/api/vision': typeof ApiVisionRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/tts/elevenlabs': typeof ApiTtsElevenlabsRoute
  '/api/tts/lovable': typeof ApiTtsLovableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ar': typeof AuthenticatedArRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/screen': typeof AuthenticatedScreenRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/vision': typeof AuthenticatedVisionRoute
  '/api/chat': typeof ApiChatRoute
  '/api/edit-image': typeof ApiEditImageRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/generate-video': typeof ApiGenerateVideoRoute
  '/api/stt': typeof ApiSttRoute
  '/api/vision': typeof ApiVisionRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/tts/elevenlabs': typeof ApiTtsElevenlabsRoute
  '/api/tts/lovable': typeof ApiTtsLovableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ar'
    | '/chat'
    | '/library'
    | '/media'
    | '/reminders'
    | '/screen'
    | '/settings'
    | '/studio'
    | '/vision'
    | '/api/chat'
    | '/api/edit-image'
    | '/api/generate-image'
    | '/api/generate-video'
    | '/api/stt'
    | '/api/vision'
    | '/chat/$threadId'
    | '/api/tts/elevenlabs'
    | '/api/tts/lovable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ar'
    | '/chat'
    | '/library'
    | '/media'
    | '/reminders'
    | '/screen'
    | '/settings'
    | '/studio'
    | '/vision'
    | '/api/chat'
    | '/api/edit-image'
    | '/api/generate-image'
    | '/api/generate-video'
    | '/api/stt'
    | '/api/vision'
    | '/chat/$threadId'
    | '/api/tts/elevenlabs'
    | '/api/tts/lovable'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/ar'
    | '/_authenticated/chat'
    | '/_authenticated/library'
    | '/_authenticated/media'
    | '/_authenticated/reminders'
    | '/_authenticated/screen'
    | '/_authenticated/settings'
    | '/_authenticated/studio'
    | '/_authenticated/vision'
    | '/api/chat'
    | '/api/edit-image'
    | '/api/generate-image'
    | '/api/generate-video'
    | '/api/stt'
    | '/api/vision'
    | '/_authenticated/chat/$threadId'
    | '/api/tts/elevenlabs'
    | '/api/tts/lovable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiEditImageRoute: typeof ApiEditImageRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiGenerateVideoRoute: typeof ApiGenerateVideoRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiVisionRoute: typeof ApiVisionRoute
  ApiTtsElevenlabsRoute: typeof ApiTtsElevenlabsRoute
  ApiTtsLovableRoute: typeof ApiTtsLovableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vision': {
      id: '/api/vision'
      path: '/api/vision'
      fullPath: '/api/vision'
      preLoaderRoute: typeof ApiVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-video': {
      id: '/api/generate-video'
      path: '/api/generate-video'
      fullPath: '/api/generate-video'
      preLoaderRoute: typeof ApiGenerateVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/edit-image': {
      id: '/api/edit-image'
      path: '/api/edit-image'
      fullPath: '/api/edit-image'
      preLoaderRoute: typeof ApiEditImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vision': {
      id: '/_authenticated/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof AuthenticatedVisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/screen': {
      id: '/_authenticated/screen'
      path: '/screen'
      fullPath: '/screen'
      preLoaderRoute: typeof AuthenticatedScreenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ar': {
      id: '/_authenticated/ar'
      path: '/ar'
      fullPath: '/ar'
      preLoaderRoute: typeof AuthenticatedArRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/tts/lovable': {
      id: '/api/tts/lovable'
      path: '/api/tts/lovable'
      fullPath: '/api/tts/lovable'
      preLoaderRoute: typeof ApiTtsLovableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts/elevenlabs': {
      id: '/api/tts/elevenlabs'
      path: '/api/tts/elevenlabs'
      fullPath: '/api/tts/elevenlabs'
      preLoaderRoute: typeof ApiTtsElevenlabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedArRoute: typeof AuthenticatedArRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedScreenRoute: typeof AuthenticatedScreenRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedVisionRoute: typeof AuthenticatedVisionRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedArRoute: AuthenticatedArRoute,
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedScreenRoute: AuthenticatedScreenRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedVisionRoute: AuthenticatedVisionRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiChatRoute: ApiChatRoute,
  ApiEditImageRoute: ApiEditImageRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiGenerateVideoRoute: ApiGenerateVideoRoute,
  ApiSttRoute: ApiSttRoute,
  ApiVisionRoute: ApiVisionRoute,
  ApiTtsElevenlabsRoute: ApiTtsElevenlabsRoute,
  ApiTtsLovableRoute: ApiTtsLovableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
