/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiGenerateImageRouteImport } from './routes/api/generate-image'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as ApiTtsLovableRouteImport } from './routes/api/tts.lovable'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateImageRoute = ApiGenerateImageRouteImport.update({
  id: '/api/generate-image',
  path: '/api/generate-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiTtsLovableRoute = ApiTtsLovableRouteImport.update({
  id: '/api/tts/lovable',
  path: '/api/tts/lovable',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/$threadId',
    path: '/$threadId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/library': typeof AuthenticatedLibraryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/stt': typeof ApiSttRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/tts/lovable': typeof ApiTtsLovableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/library': typeof AuthenticatedLibraryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/stt': typeof ApiSttRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/tts/lovable': typeof ApiTtsLovableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-image': typeof ApiGenerateImageRoute
  '/api/stt': typeof ApiSttRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/api/tts/lovable': typeof ApiTtsLovableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/library'
    | '/settings'
    | '/studio'
    | '/api/chat'
    | '/api/generate-image'
    | '/api/stt'
    | '/chat/$threadId'
    | '/api/tts/lovable'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/library'
    | '/settings'
    | '/studio'
    | '/api/chat'
    | '/api/generate-image'
    | '/api/stt'
    | '/chat/$threadId'
    | '/api/tts/lovable'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/chat'
    | '/_authenticated/library'
    | '/_authenticated/settings'
    | '/_authenticated/studio'
    | '/api/chat'
    | '/api/generate-image'
    | '/api/stt'
    | '/_authenticated/chat/$threadId'
    | '/api/tts/lovable'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateImageRoute: typeof ApiGenerateImageRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsLovableRoute: typeof ApiTtsLovableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-image': {
      id: '/api/generate-image'
      path: '/api/generate-image'
      fullPath: '/api/generate-image'
      preLoaderRoute: typeof ApiGenerateImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/tts/lovable': {
      id: '/api/tts/lovable'
      path: '/api/tts/lovable'
      fullPath: '/api/tts/lovable'
      preLoaderRoute: typeof ApiTtsLovableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateImageRoute: ApiGenerateImageRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsLovableRoute: ApiTtsLovableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
